export const topics = [
  {
    id: 'numbers',
    title: 'Numbers',
    emoji: '🔢',
    words: [
      { danish: 'nul', english: 'zero', emoji: '0️⃣' },
      { danish: 'en / et', english: 'one', emoji: '1️⃣' },
      { danish: 'to', english: 'two', emoji: '2️⃣' },
      { danish: 'tre', english: 'three', emoji: '3️⃣' },
      { danish: 'fire', english: 'four', emoji: '4️⃣' },
      { danish: 'fem', english: 'five', emoji: '5️⃣' },
      { danish: 'seks', english: 'six', emoji: '6️⃣' },
      { danish: 'syv', english: 'seven', emoji: '7️⃣' },
      { danish: 'otte', english: 'eight', emoji: '8️⃣' },
      { danish: 'ni', english: 'nine', emoji: '9️⃣' },
      { danish: 'ti', english: 'ten', emoji: '🔟' },
      { danish: 'elleve', english: 'eleven', emoji: '1️⃣1️⃣' },
      { danish: 'tolv', english: 'twelve', emoji: '1️⃣2️⃣' },
      { danish: 'tretten', english: 'thirteen', emoji: '1️⃣3️⃣' },
      { danish: 'fjorten', english: 'fourteen', emoji: '1️⃣4️⃣' },
      { danish: 'femten', english: 'fifteen', emoji: '1️⃣5️⃣' },
      { danish: 'seksten', english: 'sixteen', emoji: '1️⃣6️⃣' },
      { danish: 'sytten', english: 'seventeen', emoji: '1️⃣7️⃣' },
      { danish: 'atten', english: 'eighteen', emoji: '1️⃣8️⃣' },
      { danish: 'nitten', english: 'nineteen', emoji: '1️⃣9️⃣' },
      { danish: 'tyve', english: 'twenty', emoji: '2️⃣0️⃣' },
      { danish: 'tredive', english: 'thirty', emoji: '3️⃣0️⃣' },
      { danish: 'fyrre', english: 'forty', emoji: '4️⃣0️⃣' },
      { danish: 'halvtreds', english: 'fifty', emoji: '5️⃣0️⃣' },
      { danish: 'tres', english: 'sixty', emoji: '6️⃣0️⃣' },
      { danish: 'halvfjerds', english: 'seventy', emoji: '7️⃣0️⃣' },
      { danish: 'firs', english: 'eighty', emoji: '8️⃣0️⃣' },
      { danish: 'halvfems', english: 'ninety', emoji: '9️⃣0️⃣' },
      { danish: 'hundrede', english: 'hundred', emoji: '💯' },
      { danish: 'tusind', english: 'thousand', emoji: '🔢' },
      { danish: 'million', english: 'million', emoji: '💰' },
    ]
  },
  {
    id: 'time',
    title: 'Days, Months, Seasons & Time',
    emoji: '📅',
    words: [
      { danish: 'mandag', english: 'Monday', emoji: '📅' },
      { danish: 'tirsdag', english: 'Tuesday', emoji: '📅' },
      { danish: 'onsdag', english: 'Wednesday', emoji: '📅' },
      { danish: 'torsdag', english: 'Thursday', emoji: '📅' },
      { danish: 'fredag', english: 'Friday', emoji: '📅' },
      { danish: 'lørdag', english: 'Saturday', emoji: '📅' },
      { danish: 'søndag', english: 'Sunday', emoji: '📅' },
      { danish: 'januar', english: 'January', emoji: '❄️' },
      { danish: 'februar', english: 'February', emoji: '❄️' },
      { danish: 'marts', english: 'March', emoji: '🌱' },
      { danish: 'april', english: 'April', emoji: '🌸' },
      { danish: 'maj', english: 'May', emoji: '🌺' },
      { danish: 'juni', english: 'June', emoji: '☀️' },
      { danish: 'juli', english: 'July', emoji: '☀️' },
      { danish: 'august', english: 'August', emoji: '☀️' },
      { danish: 'september', english: 'September', emoji: '🍂' },
      { danish: 'oktober', english: 'October', emoji: '🍂' },
      { danish: 'november', english: 'November', emoji: '🍂' },
      { danish: 'december', english: 'December', emoji: '🎄' },
      { danish: 'forår', english: 'spring', emoji: '🌸' },
      { danish: 'sommer', english: 'summer', emoji: '☀️' },
      { danish: 'efterår', english: 'autumn', emoji: '🍂' },
      { danish: 'vinter', english: 'winter', emoji: '❄️' },
      { danish: 'et sekund', english: 'a second', emoji: '⏱️' },
      { danish: 'et minut', english: 'a minute', emoji: '⏱️' },
      { danish: 'et kvarter', english: 'a quarter hour / 15 minutes', emoji: '🕒' },
      { danish: 'en halv time', english: 'half an hour / 30 minutes', emoji: '🕧' },
      { danish: 'en time', english: 'an hour', emoji: '🕐' },
      { danish: 'et døgn', english: 'a day / 24 hours', emoji: '🌗' },
      { danish: 'morgen', english: 'morning', emoji: '🌅' },
      { danish: 'om morgenen', english: 'in the morning', emoji: '🌅' },
      { danish: 'formiddag', english: 'late morning / before noon', emoji: '☀️' },
      { danish: 'om formiddagen', english: 'in the late morning / before noon', emoji: '☀️' },
      { danish: 'middag', english: 'noon / midday', emoji: '🌞' },
      { danish: 'frokost', english: 'lunch', emoji: '🥪' },
      { danish: 'eftermiddag', english: 'afternoon', emoji: '🌤️' },
      { danish: 'om eftermiddagen', english: 'in the afternoon', emoji: '🌤️' },
      { danish: 'aften', english: 'evening', emoji: '🌆' },
      { danish: 'om aftenen', english: 'in the evening', emoji: '🌆' },
      { danish: 'nat', english: 'night', emoji: '🌙' },
      { danish: 'om natten', english: 'at night', emoji: '🌙' },
      { danish: 'midnat', english: 'midnight', emoji: '🌑' },
      { danish: 'over', english: 'past', emoji: '↪️' },
      { danish: 'i', english: 'to / before', emoji: '↩️' },
      { danish: 'kvart over', english: 'quarter past', emoji: '🕒' },
      { danish: 'halv', english: 'half to', emoji: '🕧' },
      { danish: 'kvart i', english: 'quarter to', emoji: '🕘' },
      { danish: 'Hvad er klokken?', english: 'What time is it?', emoji: '❓' },
      { danish: 'Den er ...', english: 'It is ...', emoji: '💬' },
    ]
  },
  {
    id: 'food',
    title: 'Food & Drinks',
    emoji: '🍽️',
    words: [
      { danish: 'et æble', english: 'apple', emoji: '🍎' },
      { danish: 'en pære', english: 'pear', emoji: '🍐' },
      { danish: 'en vindrue', english: 'grape', emoji: '🍇' },
      { danish: 'en ananas', english: 'pineapple', emoji: '🍍' },
      { danish: 'et kirsebær', english: 'cherry', emoji: '🍒' },
      { danish: 'et jordbær', english: 'strawberry', emoji: '🍓' },
      { danish: 'en appelsin', english: 'orange', emoji: '🍊' },
      { danish: 'en banan', english: 'banana', emoji: '🍌' },
      { danish: 'en citron', english: 'lemon', emoji: '🍋' },
      { danish: 'en agurk', english: 'cucumber', emoji: '🥒' },
      { danish: 'en tomat', english: 'tomato', emoji: '🍅' },
      { danish: 'en avocado', english: 'avocado', emoji: '🥑' },
      { danish: 'salat', english: 'lettuce / salad', emoji: '🥗' },
      { danish: 'en porre', english: 'leek', emoji: '🌿' },
      { danish: 'en gulerod', english: 'carrot', emoji: '🥕' },
      { danish: 'en kartoffel', english: 'potato', emoji: '🥔' },
      { danish: 'en aubergine', english: 'eggplant', emoji: '🍆' },
      { danish: 'en peberfrugt', english: 'bell pepper', emoji: '🫑' },
      { danish: 'persille', english: 'parsley', emoji: '🌿' },
      { danish: 'et hvidløg', english: 'garlic', emoji: '🧄' },
      { danish: 'et løg', english: 'onion', emoji: '🧅' },
      { danish: 'en chili', english: 'chili', emoji: '🌶️' },
      { danish: 'lammekød', english: 'lamb meat', emoji: '🥩' },
      { danish: 'en pølse', english: 'sausage', emoji: '🌭' },
      { danish: 'en kylling', english: 'chicken', emoji: '🍗' },
      { danish: 'sardiner', english: 'sardines', emoji: '🐟' },
      { danish: 'marinerede sild', english: 'marinated herring', emoji: '🐟' },
      { danish: 'en laks', english: 'salmon', emoji: '🍣' },
      { danish: 'rejer', english: 'shrimp', emoji: '🍤' },
      { danish: 'en sodavand', english: 'soda', emoji: '🥤' },
      { danish: 'en øl', english: 'beer', emoji: '🍺' },
      { danish: 'juice', english: 'juice', emoji: '🧃' },
      { danish: 'vin', english: 'wine', emoji: '🍷' },
      { danish: 'mælk', english: 'milk', emoji: '🥛' },
      { danish: 'yoghurt', english: 'yogurt', emoji: '🥛' },
      { danish: 'et æg', english: 'egg', emoji: '🥚' },
      { danish: 'en ost', english: 'cheese', emoji: '🧀' },
      { danish: 'smør', english: 'butter', emoji: '🧈' },
      { danish: 'fløde', english: 'cream', emoji: '🥛' },
      { danish: 'et franskbrød', english: 'baguette', emoji: '🥖' },
      { danish: 'et rugbrød', english: 'rye bread', emoji: '🍞' },
      { danish: 'en bolle', english: 'bun / roll', emoji: '🫓' },
      { danish: 'en kage', english: 'cake', emoji: '🎂' },
      { danish: 'chokolade', english: 'chocolate', emoji: '🍫' },
      { danish: 'en is', english: 'ice cream', emoji: '🍦' },
      { danish: 'et bolsje', english: 'candy', emoji: '🍬' },
      { danish: 'olie', english: 'oil', emoji: '🫙' },
      { danish: 'sukker', english: 'sugar', emoji: '🍬' },
      { danish: 'mel', english: 'flour', emoji: '🌾' },
      { danish: 'ris', english: 'rice', emoji: '🍚' },
      { danish: 'syltetøj', english: 'jam', emoji: '🍓' },
      { danish: 'en dåse', english: 'a can', emoji: '🥫' },
      { danish: 'en indkøbsvogn', english: 'shopping cart', emoji: '🛒' },
      { danish: 'champignon', english: 'mushroom', emoji: '🍄' },
      { danish: 'blomkål', english: 'cauliflower', emoji: '🥦' },
      { danish: 'bønner', english: 'beans', emoji: '🫘' },
      { danish: 'majs', english: 'corn', emoji: '🌽' },
      { danish: 'ærter', english: 'peas', emoji: '🫛' },
    ]
  },
  {
    id: 'weather',
    title: 'Weather',
    emoji: '🌦️',
    words: [
      { id: 'sunny', icon: 'sun', danish: 'Solen skinner', english: 'The sun is shining', emoji: '☀️' },
      { id: 'cloudy', icon: 'cloud-sun', danish: 'Det er skyet', english: 'It is cloudy', emoji: '🌤️' },
      { id: 'overcast', icon: 'cloud', danish: 'Det er overskyet', english: 'It is overcast', emoji: '☁️' },
      { id: 'rain', icon: 'rain', danish: 'Det regner', english: 'It is raining', emoji: '🌧️' },
      { id: 'wind', icon: 'wind', danish: 'Det blæser', english: 'It is windy', emoji: '💨' },
      { id: 'snow', icon: 'snow', danish: 'Det sner', english: 'It is snowing', emoji: '🌨️' },
      { id: 'storm', icon: 'storm', danish: 'Det lyner og tordner', english: 'There is lightning and thunder', emoji: '⛈️' },
    ]
  },
  {
    id: 'housing',
    title: 'Home & Housing',
    emoji: '🏠',
    words: [
      { danish: 'en lejlighed', english: 'an apartment', emoji: '🏢' },
      { danish: 'et hus', english: 'a house', emoji: '🏠' },
      { danish: 'en ejendom', english: 'a property / building', emoji: '🏘️' },
      { danish: 'en opgang', english: 'an entrance / stairwell', emoji: '🚪' },
      { danish: 'et kollegieværelse', english: 'a dorm room', emoji: '🛏️' },
      { danish: 'et hus i byen', english: 'a house in town', emoji: '🏙️' },
      { danish: 'et hus på landet', english: 'a house in the countryside', emoji: '🌾' },
      { danish: 'en stue', english: 'a living room', emoji: '🛋️' },
      { danish: 'et værelse', english: 'a room', emoji: '🚪' },
      { danish: 'et køkken', english: 'a kitchen', emoji: '🍳' },
      { danish: 'en kælder', english: 'a basement', emoji: '📦' },
      { danish: 'en entré', english: 'an entrance hall', emoji: '🚪' },
      { danish: 'en gang', english: 'a hallway', emoji: '↔️' },
      { danish: 'en spisestue', english: 'a dining room', emoji: '🍽️' },
      { danish: 'et bryggers', english: 'a utility room', emoji: '🧺' },
      { danish: 'et badeværelse', english: 'a bathroom', emoji: '🚿' },
      { danish: 'et toilet', english: 'a toilet', emoji: '🚽' },
      { danish: 'et soveværelse', english: 'a bedroom', emoji: '🛏️' },
      { danish: 'et børneværelse', english: "a children's room", emoji: '🧸' },
      { danish: 'et kontor', english: 'an office', emoji: '💻' },
      { danish: 'et arbejdsværelse', english: 'a study / workroom', emoji: '📚' },
      { danish: 'taget / loftet', english: 'the roof / attic', emoji: '🔺' },
      { danish: 'stuen', english: 'the ground floor', emoji: '1️⃣' },
      { danish: 'kælderen', english: 'the basement', emoji: '📦' },
      { danish: 'første sal', english: 'first floor', emoji: '2️⃣' },
      { danish: 'anden sal', english: 'second floor', emoji: '3️⃣' },
      { danish: 'tredje sal', english: 'third floor', emoji: '4️⃣' },
      { danish: 'en husleje', english: 'rent', emoji: '💸' },
      { danish: 'et depositum', english: 'a deposit', emoji: '🔑' },
      { danish: 'vand, varme, el', english: 'water, heating, electricity', emoji: '💧' },
      { danish: 'kvadratmeter', english: 'square meters', emoji: '📐' },
      { danish: 'en udlejer', english: 'a landlord', emoji: '🧑‍💼' },
      { danish: 'at leje', english: 'to rent', emoji: '📝' },
      { danish: 'at dele', english: 'to share', emoji: '🤝' },
      { danish: 'at betale', english: 'to pay', emoji: '💳' },
      { danish: 'en hvid sofa', english: 'a white sofa', emoji: '🛋️' },
      { danish: 'den er hvid', english: 'it is white', emoji: '⚪' },
      { danish: 'et hvidt bord', english: 'a white table', emoji: '⚪' },
      { danish: 'det er hvidt', english: 'it is white', emoji: '⚪' },
      { danish: 'tre hvide blomster', english: 'three white flowers', emoji: '💐' },
      { danish: 'de er hvide', english: 'they are white', emoji: '⚪' },
      { danish: 'et køkkenbord', english: 'a kitchen counter', emoji: '🔪' },
      { danish: 'et køleskab', english: 'a refrigerator', emoji: '🧊' },
      { danish: 'en fryser', english: 'a freezer', emoji: '❄️' },
      { danish: 'et komfur', english: 'a stove', emoji: '🔥' },
      { danish: 'en ovn', english: 'an oven', emoji: '🔥' },
      { danish: 'et køkkenskab', english: 'a kitchen cabinet', emoji: '🗄️' },
      { danish: 'en skuffe', english: 'a drawer', emoji: '🗄️' },
      { danish: 'en thermokande', english: 'a thermos jug', emoji: '☕' },
      { danish: 'en tallerken', english: 'a plate', emoji: '🍽️' },
      { danish: 'en kniv', english: 'a knife', emoji: '🔪' },
      { danish: 'en gaffel', english: 'a fork', emoji: '🍴' },
      { danish: 'en ske', english: 'a spoon', emoji: '🥄' },
      { danish: 'en elkedel', english: 'an electric kettle', emoji: '🫖' },
      { danish: 'en køkkenvask', english: 'a kitchen sink', emoji: '🚰' },
      { danish: 'en emhætte', english: 'an extractor hood', emoji: '💨' },
      { danish: 'en potteplante', english: 'a potted plant', emoji: '🪴' },
      { danish: 'et gardin', english: 'a curtain', emoji: '🪟' },
      { danish: 'et skærebræt', english: 'a cutting board', emoji: '🔪' },
      { danish: 'en bruseniche', english: 'a shower stall', emoji: '🚿' },
      { danish: 'en bruser', english: 'a shower', emoji: '🚿' },
      { danish: 'en håndvask', english: 'a sink / washbasin', emoji: '🚰' },
      { danish: 'en vandhane', english: 'a tap / faucet', emoji: '🚰' },
      { danish: 'et spejl', english: 'a mirror', emoji: '🪞' },
      { danish: 'en hylde', english: 'a shelf', emoji: '🧴' },
      { danish: 'en toiletrulle', english: 'a toilet roll', emoji: '🧻' },
      { danish: 'en bademåtte', english: 'a bath mat', emoji: '🧼' },
      { danish: 'et badeforhæng', english: 'a shower curtain', emoji: '🚿' },
      { danish: 'et håndklæde', english: 'a towel', emoji: '🧺' },
      { danish: 'en hårtørrer', english: 'a hair dryer', emoji: '💨' },
      { danish: 'en tandbørste', english: 'a toothbrush', emoji: '🪥' },
      { danish: 'en sæbe', english: 'a soap', emoji: '🧼' },
      { danish: 'en knagerække', english: 'a coat rack / row of hooks', emoji: '🪝' },
    ]
  }
  , // asdasd // asdasdasda
  {
    id: 'verbs',
    title: 'Verbs',
    emoji: '⚡',
    comingSoon: false,
    words: [],
    verbs: [
      { imperativ: 'aflever', infinitiv: 'aflevere', praesens: 'afleverer', imperfektum: 'afleverede', perfektum: 'har afleveret', english: 'hand in / deliver' },
      { imperativ: 'arbejd', infinitiv: 'arbejde', praesens: 'arbejder', imperfektum: 'arbejdede', perfektum: 'har arbejdet', english: 'work' },
      { imperativ: 'barber', infinitiv: 'barbere', praesens: 'barberer', imperfektum: 'barberede', perfektum: 'har barberet', english: 'shave' },
      { imperativ: 'begynd', infinitiv: 'begynde', praesens: 'begynder', imperfektum: 'begyndte', perfektum: 'har begyndt', english: 'begin / start' },
      { imperativ: 'besøg', infinitiv: 'besøge', praesens: 'besøger', imperfektum: 'besøgte', perfektum: 'har besøgt', english: 'visit' },
      { imperativ: 'betal', infinitiv: 'betale', praesens: 'betaler', imperfektum: 'betalte', perfektum: 'har betalt', english: 'pay' },
      { imperativ: 'bliv', infinitiv: 'blive', praesens: 'bliver', imperfektum: 'blev', perfektum: 'er blevet', english: 'become / stay' },
      { imperativ: 'blæs', infinitiv: 'blæse', praesens: 'blæser', imperfektum: 'blæste', perfektum: 'har blæst', english: 'blow' },
      { imperativ: 'bo', infinitiv: 'bo', praesens: 'bor', imperfektum: 'boede', perfektum: 'har boet', english: 'live / reside' },
      { imperativ: 'brug', infinitiv: 'bruge', praesens: 'bruger', imperfektum: 'brugte', perfektum: 'har brugt', english: 'use' },
      { imperativ: 'cykl', infinitiv: 'cykle', praesens: 'cykler', imperfektum: 'cyklede', perfektum: 'er/har cyklet', english: 'cycle / bike' },
      { imperativ: 'dans', infinitiv: 'danse', praesens: 'danser', imperfektum: 'dansede', perfektum: 'har danset', english: 'dance' },
      { imperativ: 'del', infinitiv: 'dele', praesens: 'deler', imperfektum: 'delte', perfektum: 'har delt', english: 'share / divide' },
      { imperativ: 'drik', infinitiv: 'drikke', praesens: 'drikker', imperfektum: 'drak', perfektum: 'har drukket', english: 'drink' },
      { imperativ: 'dyrk', infinitiv: 'dyrke', praesens: 'dyrker', imperfektum: 'dyrkede', perfektum: 'har dyrket', english: 'cultivate / practice' },
      { imperativ: 'elsk', infinitiv: 'elske', praesens: 'elsker', imperfektum: 'elskede', perfektum: 'har elsket', english: 'love' },
      { imperativ: 'find', infinitiv: 'finde', praesens: 'finder', imperfektum: 'fandt', perfektum: 'har fundet', english: 'find' },
      { imperativ: 'flytt', infinitiv: 'flytte', praesens: 'flytter', imperfektum: 'flyttede', perfektum: 'er/har flyttet', english: 'move' },
      { imperativ: 'forstå', infinitiv: 'forstå', praesens: 'forstår', imperfektum: 'forstod', perfektum: 'har forstået', english: 'understand' },
      { imperativ: 'forklar', infinitiv: 'forklare', praesens: 'forklarer', imperfektum: 'forklarede', perfektum: 'har forklaret', english: 'explain' },
      { imperativ: 'få', infinitiv: 'få', praesens: 'får', imperfektum: 'fik', perfektum: 'har fået', english: 'get / receive' },
      { imperativ: 'gid', infinitiv: 'gide', praesens: 'gider', imperfektum: 'gad', perfektum: 'har gidet', english: 'bother to / feel like' },
      { imperativ: 'giv', infinitiv: 'give', praesens: 'giver', imperfektum: 'gav', perfektum: 'har givet', english: 'give' },
      { imperativ: 'glæd', infinitiv: 'glæde', praesens: 'glæder', imperfektum: 'glædede', perfektum: 'har glædet', english: 'please / make happy' },
      { imperativ: 'googl', infinitiv: 'google', praesens: 'googler', imperfektum: 'googlede', perfektum: 'har googlet', english: 'google' },
      { imperativ: 'gør', infinitiv: 'gøre', praesens: 'gør', imperfektum: 'gjorde', perfektum: 'har gjort', english: 'do / make' },
      { imperativ: 'gå', infinitiv: 'gå', praesens: 'går', imperfektum: 'gik', perfektum: 'er/har gået', english: 'go / walk' },
      { imperativ: 'hav', infinitiv: 'have', praesens: 'har', imperfektum: 'havde', perfektum: 'er/har haft', english: 'have' },
      { imperativ: 'hed', infinitiv: 'hedde', praesens: 'hedder', imperfektum: 'hed', perfektum: 'har heddet', english: 'be called' },
      { imperativ: 'hent', infinitiv: 'hente', praesens: 'henter', imperfektum: 'hentede', perfektum: 'har hentet', english: 'fetch / pick up' },
      { imperativ: 'hjælp', infinitiv: 'hjælpe', praesens: 'hjælper', imperfektum: 'hjalp', perfektum: 'har hjulpet', english: 'help' },
      { imperativ: 'hyg', infinitiv: 'hygge', praesens: 'hygger', imperfektum: 'hyggede', perfektum: 'har hygget', english: 'enjoy / cozy up' },
      { imperativ: 'hæng', infinitiv: 'hænge', praesens: 'hænger', imperfektum: 'hang', perfektum: 'har hængt', english: 'hang' },
      { imperativ: 'hør', infinitiv: 'høre', praesens: 'hører', imperfektum: 'hørte', perfektum: 'har hørt', english: 'hear / listen' },
      { imperativ: 'interesser', infinitiv: 'interessere', praesens: 'interesserer', imperfektum: 'interesserede', perfektum: 'har interesseret', english: 'interest' },
      { imperativ: 'inviter', infinitiv: 'invitere', praesens: 'inviterer', imperfektum: 'inviterede', perfektum: 'har inviteret', english: 'invite' },
      { imperativ: 'kend', infinitiv: 'kende', praesens: 'kender', imperfektum: 'kendte', perfektum: 'har kendt', english: 'know / recognize' },
      { imperativ: 'kig', infinitiv: 'kigge', praesens: 'kigger', imperfektum: 'kiggede', perfektum: 'har kigget', english: 'look / watch' },
      { imperativ: 'klar', infinitiv: 'klare', praesens: 'klarer', imperfektum: 'klarede', perfektum: 'har klaret', english: 'manage / handle' },
      { imperativ: 'kom', infinitiv: 'komme', praesens: 'kommer', imperfektum: 'kom', perfektum: 'er kommet', english: 'come' },
      { imperativ: 'kost', infinitiv: 'koste', praesens: 'koster', imperfektum: 'kostede', perfektum: 'har kostet', english: 'cost' },
      { imperativ: 'køb', infinitiv: 'købe', praesens: 'køber', imperfektum: 'købte', perfektum: 'har købt', english: 'buy' },
      { imperativ: 'kør', infinitiv: 'køre', praesens: 'kører', imperfektum: 'kørte', perfektum: 'har kørt', english: 'drive / ride' },
      { imperativ: 'larm', infinitiv: 'larme', praesens: 'larmer', imperfektum: 'larmede', perfektum: 'har larmet', english: 'make noise' },
      { imperativ: 'lav', infinitiv: 'lave', praesens: 'laver', imperfektum: 'lavede', perfektum: 'har lavet', english: 'make / do' },
      { imperativ: 'leg', infinitiv: 'lege', praesens: 'leger', imperfektum: 'legede', perfektum: 'har leget', english: 'play' },
      { imperativ: 'lev', infinitiv: 'leve', praesens: 'lever', imperfektum: 'levede', perfektum: 'har levet', english: 'live' },
      { imperativ: 'ligg', infinitiv: 'ligge', praesens: 'ligger', imperfektum: 'lå', perfektum: 'har ligget', english: 'lie (down)' },
      { imperativ: 'luk', infinitiv: 'lukke', praesens: 'lukker', imperfektum: 'lukkede', perfektum: 'har lukket', english: 'close / shut' },
      { imperativ: 'lyd', infinitiv: 'lyde', praesens: 'lyder', imperfektum: 'lød', perfektum: 'har lydt', english: 'sound' },
      { imperativ: 'lyt', infinitiv: 'lytte', praesens: 'lytter', imperfektum: 'lyttede', perfektum: 'har lyttet', english: 'listen' },
      { imperativ: 'lær', infinitiv: 'lære', praesens: 'lærer', imperfektum: 'lærte', perfektum: 'har lært', english: 'learn / teach' },
      { imperativ: 'læs', infinitiv: 'læse', praesens: 'læser', imperfektum: 'læste', perfektum: 'har læst', english: 'read' },
      { imperativ: 'løb', infinitiv: 'løbe', praesens: 'løber', imperfektum: 'løb', perfektum: 'er/har løbet', english: 'run' },
      { imperativ: 'mød', infinitiv: 'møde', praesens: 'møder', imperfektum: 'mødte', perfektum: 'har mødt', english: 'meet' },
      { imperativ: 'nyd', infinitiv: 'nyde', praesens: 'nyder', imperfektum: 'nød', perfektum: 'har nydt', english: 'enjoy' },
      { imperativ: 'nå', infinitiv: 'nå', praesens: 'når', imperfektum: 'nåede', perfektum: 'har nået', english: 'reach / catch' },
      { imperativ: 'ønsk', infinitiv: 'ønske', praesens: 'ønsker', imperfektum: 'ønskede', perfektum: 'har ønsket', english: 'wish' },
      { imperativ: 'øv', infinitiv: 'øve', praesens: 'øver', imperfektum: 'øvede', perfektum: 'har øvet', english: 'practice' },
      { imperativ: 'pas', infinitiv: 'passe', praesens: 'passer', imperfektum: 'passede', perfektum: 'har passet', english: 'fit / suit / look after' },
      { imperativ: 'planlæg', infinitiv: 'planlægge', praesens: 'planlægger', imperfektum: 'planlagde', perfektum: 'har planlagt', english: 'plan' },
      { imperativ: 'prøv', infinitiv: 'prøve', praesens: 'prøver', imperfektum: 'prøvede', perfektum: 'har prøvet', english: 'try' },
      { imperativ: 'regn', infinitiv: 'regne', praesens: 'regner', imperfektum: 'regnede', perfektum: 'har regnet', english: 'rain / calculate' },
      { imperativ: 'rejs', infinitiv: 'rejse', praesens: 'rejser', imperfektum: 'rejste', perfektum: 'er/har rejst', english: 'travel' },
      { imperativ: 'ring', infinitiv: 'ringe', praesens: 'ringer', imperfektum: 'ringede', perfektum: 'har ringet', english: 'ring / call' },
      { imperativ: 'ryd op', infinitiv: 'rydde op', praesens: 'rydder op', imperfektum: 'ryddede op', perfektum: 'har ryddet op', english: 'tidy up / clean up' },
      { imperativ: 'ryg', infinitiv: 'ryge', praesens: 'ryger', imperfektum: 'røg', perfektum: 'har røget', english: 'smoke' },
      { imperativ: 'savn', infinitiv: 'savne', praesens: 'savner', imperfektum: 'savnede', perfektum: 'har savnet', english: 'miss' },
      { imperativ: 'se', infinitiv: 'se', praesens: 'ser', imperfektum: 'så', perfektum: 'har set', english: 'see / watch' },
      { imperativ: 'send', infinitiv: 'sende', praesens: 'sender', imperfektum: 'sendte', perfektum: 'har sendt', english: 'send' },
      { imperativ: 'sid', infinitiv: 'sidde', praesens: 'sidder', imperfektum: 'sad', perfektum: 'har siddet', english: 'sit' },
      { imperativ: 'sig', infinitiv: 'sige', praesens: 'siger', imperfektum: 'sagde', perfektum: 'har sagt', english: 'say' },
      { imperativ: 'skift', infinitiv: 'skifte', praesens: 'skifter', imperfektum: 'skiftede', perfektum: 'har skiftet', english: 'change / switch' },
      { imperativ: 'skin', infinitiv: 'skinne', praesens: 'skinner', imperfektum: 'skinnede', perfektum: 'har skinnet', english: 'shine' },
      { imperativ: 'skriv', infinitiv: 'skrive', praesens: 'skriver', imperfektum: 'skrev', perfektum: 'har skrevet', english: 'write' },
      { imperativ: 'skynd', infinitiv: 'skynde', praesens: 'skynder', imperfektum: 'skyndte', perfektum: 'har skyndt', english: 'hurry' },
      { imperativ: 'slap af', infinitiv: 'slappe af', praesens: 'slapper af', imperfektum: 'slappede af', perfektum: 'har slappet af', english: 'relax' },
      { imperativ: 'sluk', infinitiv: 'slukke', praesens: 'slukker', imperfektum: 'slukkede', perfektum: 'har slukket', english: 'turn off / extinguish' },
      { imperativ: 'smag', infinitiv: 'smage', praesens: 'smager', imperfektum: 'smagte', perfektum: 'har smagt', english: 'taste' },
      { imperativ: 'snak', infinitiv: 'snakke', praesens: 'snakker', imperfektum: 'snakkede', perfektum: 'har snakket', english: 'talk / chat' },
      { imperativ: 'sov', infinitiv: 'sove', praesens: 'sover', imperfektum: 'sov', perfektum: 'har sovet', english: 'sleep' },
      { imperativ: 'spil', infinitiv: 'spille', praesens: 'spiller', imperfektum: 'spillede', perfektum: 'har spillet', english: 'play (game/music)' },
      { imperativ: 'spis', infinitiv: 'spise', praesens: 'spiser', imperfektum: 'spiste', perfektum: 'har spist', english: 'eat' },
      { imperativ: 'spørg', infinitiv: 'spørge', praesens: 'spørger', imperfektum: 'spurgte', perfektum: 'har spurgt', english: 'ask' },
      { imperativ: 'start', infinitiv: 'starte', praesens: 'starter', imperfektum: 'startede', perfektum: 'er/har startet', english: 'start' },
      { imperativ: 'stop', infinitiv: 'stoppe', praesens: 'stopper', imperfektum: 'stoppede', perfektum: 'er/har stoppet', english: 'stop' },
      { imperativ: 'stå', infinitiv: 'stå', praesens: 'står', imperfektum: 'stod', perfektum: 'har stået', english: 'stand' },
      { imperativ: 'svar', infinitiv: 'svare', praesens: 'svarer', imperfektum: 'svarede', perfektum: 'har svaret', english: 'answer / reply' },
      { imperativ: 'svøm', infinitiv: 'svømme', praesens: 'svømmer', imperfektum: 'svømmede', perfektum: 'har svømmet', english: 'swim' },
      { imperativ: '-', infinitiv: 'synes', praesens: 'synes', imperfektum: 'syntes', perfektum: 'har syntes', english: 'think / seem' },
      { imperativ: 'sælg', infinitiv: 'sælge', praesens: 'sælger', imperfektum: 'solgte', perfektum: 'har solgt', english: 'sell' },
      { imperativ: 'sæt', infinitiv: 'sætte', praesens: 'sætter', imperfektum: 'satte', perfektum: 'har sat', english: 'put / place / set' },
      { imperativ: 'søg', infinitiv: 'søge', praesens: 'søger', imperfektum: 'søgte', perfektum: 'har søgt', english: 'search' },
      { imperativ: 'tag', infinitiv: 'tage', praesens: 'tager', imperfektum: 'tog', perfektum: 'har taget', english: 'take' },
      { imperativ: 'tal', infinitiv: 'tale', praesens: 'taler', imperfektum: 'talte', perfektum: 'har talt', english: 'speak / talk' },
      { imperativ: 'tjek', infinitiv: 'tjekke', praesens: 'tjekker', imperfektum: 'tjekkede', perfektum: 'har tjekket', english: 'check' },
      { imperativ: 'tro', infinitiv: 'tro', praesens: 'tror', imperfektum: 'troede', perfektum: 'har troet', english: 'believe / think' },
      { imperativ: 'træn', infinitiv: 'træne', praesens: 'træner', imperfektum: 'trænede', perfektum: 'har trænet', english: 'train / exercise' },
      { imperativ: 'tænd', infinitiv: 'tænde', praesens: 'tænder', imperfektum: 'tændte', perfektum: 'har tændt', english: 'turn on / light' },
      { imperativ: 'tænk', infinitiv: 'tænke', praesens: 'tænker', imperfektum: 'tænkte', perfektum: 'har tænkt', english: 'think' },
      { imperativ: 'vask', infinitiv: 'vaske', praesens: 'vasker', imperfektum: 'vaskede', perfektum: 'har vasket', english: 'wash' },
      { imperativ: 'vent', infinitiv: 'vente', praesens: 'venter', imperfektum: 'ventede', perfektum: 'har ventet', english: 'wait' },
      { imperativ: 'væk', infinitiv: 'vække', praesens: 'vækker', imperfektum: 'vækkede', perfektum: 'har vækket', english: 'wake (someone) up' },
      { imperativ: 'vågn', infinitiv: 'vågne', praesens: 'vågner', imperfektum: 'vågnede', perfektum: 'er vågnet', english: 'wake up' },
      { imperativ: 'åbn', infinitiv: 'åbne', praesens: 'åbner', imperfektum: 'åbnede', perfektum: 'har åbnet', english: 'open' },
    ]
  }
]
