export const topics = [
  {
    id: 'numbers',
    title: 'Numbers',
    emoji: '🔢',
    words: [
      { danish: 'nul', english: 'zero', emoji: '0️⃣' },
      { danish: 'en / et', english: 'one', emoji: '1️⃣' },
      { danish: 'to', english: 'two', emoji: '2️⃣' },
      { danish: 'tre', english: 'three', emoji: '3️⃣' },
      { danish: 'fire', english: 'four', emoji: '4️⃣' },
      { danish: 'fem', english: 'five', emoji: '5️⃣' },
      { danish: 'seks', english: 'six', emoji: '6️⃣' },
      { danish: 'syv', english: 'seven', emoji: '7️⃣' },
      { danish: 'otte', english: 'eight', emoji: '8️⃣' },
      { danish: 'ni', english: 'nine', emoji: '9️⃣' },
      { danish: 'ti', english: 'ten', emoji: '🔟' },
      { danish: 'elleve', english: 'eleven', emoji: '1️⃣1️⃣' },
      { danish: 'tolv', english: 'twelve', emoji: '1️⃣2️⃣' },
      { danish: 'tretten', english: 'thirteen', emoji: '1️⃣3️⃣' },
      { danish: 'fjorten', english: 'fourteen', emoji: '1️⃣4️⃣' },
      { danish: 'femten', english: 'fifteen', emoji: '1️⃣5️⃣' },
      { danish: 'seksten', english: 'sixteen', emoji: '1️⃣6️⃣' },
      { danish: 'sytten', english: 'seventeen', emoji: '1️⃣7️⃣' },
      { danish: 'atten', english: 'eighteen', emoji: '1️⃣8️⃣' },
      { danish: 'nitten', english: 'nineteen', emoji: '1️⃣9️⃣' },
      { danish: 'tyve', english: 'twenty', emoji: '2️⃣0️⃣' },
      { danish: 'tredive', english: 'thirty', emoji: '3️⃣0️⃣' },
      { danish: 'fyrre', english: 'forty', emoji: '4️⃣0️⃣' },
      { danish: 'halvtreds', english: 'fifty', emoji: '5️⃣0️⃣' },
      { danish: 'tres', english: 'sixty', emoji: '6️⃣0️⃣' },
      { danish: 'halvfjerds', english: 'seventy', emoji: '7️⃣0️⃣' },
      { danish: 'firs', english: 'eighty', emoji: '8️⃣0️⃣' },
      { danish: 'halvfems', english: 'ninety', emoji: '9️⃣0️⃣' },
      { danish: 'hundrede', english: 'hundred', emoji: '💯' },
      { danish: 'tusind', english: 'thousand', emoji: '🔢' },
      { danish: 'million', english: 'million', emoji: '💰' },
    ]
  },
  {
    id: 'time',
    title: 'Days, Months & Seasons',
    emoji: '📅',
    words: [
      { danish: 'mandag', english: 'Monday', emoji: '📅' },
      { danish: 'tirsdag', english: 'Tuesday', emoji: '📅' },
      { danish: 'onsdag', english: 'Wednesday', emoji: '📅' },
      { danish: 'torsdag', english: 'Thursday', emoji: '📅' },
      { danish: 'fredag', english: 'Friday', emoji: '📅' },
      { danish: 'lørdag', english: 'Saturday', emoji: '📅' },
      { danish: 'søndag', english: 'Sunday', emoji: '📅' },
      { danish: 'januar', english: 'January', emoji: '❄️' },
      { danish: 'februar', english: 'February', emoji: '❄️' },
      { danish: 'marts', english: 'March', emoji: '🌱' },
      { danish: 'april', english: 'April', emoji: '🌸' },
      { danish: 'maj', english: 'May', emoji: '🌺' },
      { danish: 'juni', english: 'June', emoji: '☀️' },
      { danish: 'juli', english: 'July', emoji: '☀️' },
      { danish: 'august', english: 'August', emoji: '☀️' },
      { danish: 'september', english: 'September', emoji: '🍂' },
      { danish: 'oktober', english: 'October', emoji: '🍂' },
      { danish: 'november', english: 'November', emoji: '🍂' },
      { danish: 'december', english: 'December', emoji: '🎄' },
      { danish: 'forår', english: 'spring', emoji: '🌸' },
      { danish: 'sommer', english: 'summer', emoji: '☀️' },
      { danish: 'efterår', english: 'autumn', emoji: '🍂' },
      { danish: 'vinter', english: 'winter', emoji: '❄️' },
    ]
  },
  {
    id: 'food',
    title: 'Food & Drinks',
    emoji: '🍽️',
    words: [
      { danish: 'et æble', english: 'apple', emoji: '🍎' },
      { danish: 'en pære', english: 'pear', emoji: '🍐' },
      { danish: 'en vindrue', english: 'grape', emoji: '🍇' },
      { danish: 'en ananas', english: 'pineapple', emoji: '🍍' },
      { danish: 'et kirsebær', english: 'cherry', emoji: '🍒' },
      { danish: 'et jordbær', english: 'strawberry', emoji: '🍓' },
      { danish: 'en appelsin', english: 'orange', emoji: '🍊' },
      { danish: 'en banan', english: 'banana', emoji: '🍌' },
      { danish: 'en citron', english: 'lemon', emoji: '🍋' },
      { danish: 'en agurk', english: 'cucumber', emoji: '🥒' },
      { danish: 'en tomat', english: 'tomato', emoji: '🍅' },
      { danish: 'en avocado', english: 'avocado', emoji: '🥑' },
      { danish: 'salat', english: 'lettuce / salad', emoji: '🥗' },
      { danish: 'en porre', english: 'leek', emoji: '🌿' },
      { danish: 'en gulerod', english: 'carrot', emoji: '🥕' },
      { danish: 'en kartoffel', english: 'potato', emoji: '🥔' },
      { danish: 'en aubergine', english: 'eggplant', emoji: '🍆' },
      { danish: 'en peberfrugt', english: 'bell pepper', emoji: '🫑' },
      { danish: 'persille', english: 'parsley', emoji: '🌿' },
      { danish: 'et hvidløg', english: 'garlic', emoji: '🧄' },
      { danish: 'et løg', english: 'onion', emoji: '🧅' },
      { danish: 'en chili', english: 'chili', emoji: '🌶️' },
      { danish: 'lammekød', english: 'lamb meat', emoji: '🥩' },
      { danish: 'en pølse', english: 'sausage', emoji: '🌭' },
      { danish: 'en kylling', english: 'chicken', emoji: '🍗' },
      { danish: 'sardiner', english: 'sardines', emoji: '🐟' },
      { danish: 'marinerede sild', english: 'marinated herring', emoji: '🐟' },
      { danish: 'en laks', english: 'salmon', emoji: '🍣' },
      { danish: 'rejer', english: 'shrimp', emoji: '🍤' },
      { danish: 'en sodavand', english: 'soda', emoji: '🥤' },
      { danish: 'en øl', english: 'beer', emoji: '🍺' },
      { danish: 'juice', english: 'juice', emoji: '🧃' },
      { danish: 'vin', english: 'wine', emoji: '🍷' },
      { danish: 'mælk', english: 'milk', emoji: '🥛' },
      { danish: 'yoghurt', english: 'yogurt', emoji: '🥛' },
      { danish: 'et æg', english: 'egg', emoji: '🥚' },
      { danish: 'en ost', english: 'cheese', emoji: '🧀' },
      { danish: 'smør', english: 'butter', emoji: '🧈' },
      { danish: 'fløde', english: 'cream', emoji: '🥛' },
      { danish: 'et franskbrød', english: 'baguette', emoji: '🥖' },
      { danish: 'et rugbrød', english: 'rye bread', emoji: '🍞' },
      { danish: 'en bolle', english: 'bun / roll', emoji: '🫓' },
      { danish: 'en kage', english: 'cake', emoji: '🎂' },
      { danish: 'chokolade', english: 'chocolate', emoji: '🍫' },
      { danish: 'en is', english: 'ice cream', emoji: '🍦' },
      { danish: 'et bolsje', english: 'candy', emoji: '🍬' },
      { danish: 'olie', english: 'oil', emoji: '🫙' },
      { danish: 'sukker', english: 'sugar', emoji: '🍬' },
      { danish: 'mel', english: 'flour', emoji: '🌾' },
      { danish: 'ris', english: 'rice', emoji: '🍚' },
      { danish: 'syltetøj', english: 'jam', emoji: '🍓' },
      { danish: 'en dåse', english: 'a can', emoji: '🥫' },
      { danish: 'en indkøbsvogn', english: 'shopping cart', emoji: '🛒' },
      { danish: 'champignon', english: 'mushroom', emoji: '🍄' },
      { danish: 'blomkål', english: 'cauliflower', emoji: '🥦' },
      { danish: 'bønner', english: 'beans', emoji: '🫘' },
      { danish: 'majs', english: 'corn', emoji: '🌽' },
      { danish: 'ærter', english: 'peas', emoji: '🫛' },
    ]
  }
  ,
  {
    id: 'verbs',
    title: 'Verbs',
    emoji: '⚡',
    words: [],
    comingSoon: true
  }
]